apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system
spec:
  addons:
    grafana:
      enabled: true
    kiali:
      enabled: true
    prometheus:
      enabled: true
    jaeger:
      install:
        storage:
          memory:
            maxTraces: 50000
          type: Memory
  gateways:
    ingress:
      enabled: true
    openshiftRoute:
      enabled: true
  #meshConfig:
  #  extensionProviders:
  #  - name: prometheus
  #    prometheus: {}
  #  - name: otel
  #    opentelemetry:
  #      port: 4317
  #      service: otel-collector.istio-system.svc.cluster.local
  policy:
    type: Istiod
  profiles:
  - default
  proxy:
    accessLogging:
      file:
        name: /dev/stdout
    injection:
      autoInject: true
  security:
    manageNetworkPolicy: true
  telemetry:
    type: Istiod
  tracing:
    sampling: 10000
    type: Jaeger
  version: v2.6
