apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  metrics: 
  - providers:
    - name: prometheus
  tracing:
  - providers:
    - name: otel
    randomSamplingPercentage: 100
