apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
spec:
  api:
    namespaces:
      exclude: []
  auth:
    strategy: openshift
  deployment:
    accessible_namespaces: []
    ingress:
      enabled: true
    namespace: istio-system
    pod_labels:
      sidecar.istio.io/inject: "false"
  external_services:
    prometheus:
      auth:
        insecure_skip_verify: false
        type: bearer
        use_kiali_token: true
      thanos_proxy:
        enabled: true
      url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
    tracing:
      enabled: true
      provider: jaeger
      use_grpc: true
      internal_url: http://tempo-istio-tracing-tempo-query-frontend.istio-tracing-system.svc.cluster.local:16685
      external_url: https://tempo-istio-tracing-tempo-query-frontend-istio-tracing-system.apps.ocp7.sbx1.kyndryl.net
      query_timeout: 60
    istio_namespace: istio-system
    grafana:   
      enabled: false
  istio_namespace: istio-system
  version: default
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: istio-kiali-ingress
  namespace: istio-system
spec:
  ingress:
  - {}
  podSelector:
    matchLabels:
      app: kiali
  policyTypes:
  - Ingress
---

# Tempo
#    tracing:
#      enabled: true
#      provider: tempo
#      use_grpc: false
#      internal_url: http://tempo-istio-tracing-tempo-query-frontend.istio-tracing-system.svc.cluster.local:3200
#      external_url: https://tempo-istio-tracing-tempo-query-frontend-istio-tracing-system.apps.ocp7.sbx1.kyndryl.net
#      query_timeout: 60
#      namespace_selector: false

# Jaeger
#    tracing:
#      enabled: true
#      provider: jaeger
#      use_grpc: true
#      internal_url: http://tempo-istio-tracing-tempo-query-frontend.istio-tracing-system.svc.cluster.local:16685
#      external_url: https://tempo-istio-tracing-tempo-query-frontend-istio-tracing-system.apps.ocp7.sbx1.kyndryl.net
#      query_timeout: 60
